version: "3"
services:
  ethermap:
    build: .
    depends_on:
      - couchdb
    links:
      - couchdb
    ports:
      - "8080:8080"
    environment:
      DB_PORT_5984_TCP_ADDR: admin:password@couchdb
      PORT: 8080

  couchdb:
    image: couchdb:3
    volumes:
      - ./couchdb-data:/opt/couchdb/data
    # ports: # expose ports for development only
    #   - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
